backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post','get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }


    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\About;
use common\models\Category;
use common\models\Contacts;
use common\models\News;
use common\models\NewsSearch;
use common\models\Product;
use common\models\ProductSearch;
use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup', 'change-language','detail','product'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'change-language'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }



    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $lang = Yii::$app->session->get('lang', '');
        if (empty($lang)) {
            Yii::$app->session->set('lang', 'vi');
        }

        return $this->render('home', [
        ]);
    }

    public function actionProduct($title, $cateId)
    {
        $lang = Yii::$app->session->get('lang', '');
        if (empty($lang)) {
            Yii::$app->session->set('lang', 'vi');
        }
        $list_cate = Category::getListCateChild($cateId);
        //var_dump($list_cate);exit;
        $list_product = Product::getList($cateId);
        $data = [];
        foreach ($list_cate as $cate) {
            /** @var $cate Category */
            $data[] = $cate;
            foreach ($list_product as $p) {
                /** @var $p Product */
                if($cate->category_id == $p->category_id) {
                   // array_push($data[]['pro'], $p);
                    $cate->listProduct[]= $p;
                }
            }
        }

        return $this->render('index', [
            'data' => $data,
            'listCate' => $list_cate,
            'listProduct' => $list_product
        ]);
    }

    public function actionDetail($title,$prod) {
        $id = Yii::$app->request->get('prod', 0);
        $pro = Product::findOne(['id' => $id]);

        return $this->render('detail',['pro' =>$pro]);
    }

    public function actionChangeLanguage()
    {
        $lang = Yii::$app->request->get('lang', 'vi');
        Yii::$app->session->set('lang', $lang);
        //var_dump($lang);exit;
        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
       // return $this->redirect(['site/index']);
    }

    public function actionNews() {
        $searchModel = new NewsSearch();
        $dataProvider = $searchModel->searchPortal(Yii::$app->request->queryParams);

        $paging = new Pagination();
        $paging->totalCount = $dataProvider->getTotalCount();
        $paging->defaultPageSize = 10;

        return $this->render('news_list', [
            'listNews' => $dataProvider->getModels(),
            'paging' => $paging,
        ]);
    }

    public function actionNewsDetail($name, $id,$nid) {
        $news = News::findOne(['id' => $id]);
        return $this->render('news_detail', [
           'model' => $news,
        ]);
    }
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    /*public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }*/
    public function actionContact()
    {
        $model = Contacts::find()->one();
        return $this->render('contact', [
            'contact' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $ab = About::findOne(['status' => About::STATUS_ACTIVE]);
        return $this->render('about', ['about' => $ab]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */
/* @var $about \common\models\About */

use yii\helpers\Html;

$this->title = $about->getName();
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="container wrap-content">
    <section class="block-product">
        <div class="row">
            <div class="col-3">
                <div class="about-logo">
                    <img src="<?= $about->getThumb()?>" class="img-fluid" alt="">
                </div>
            </div>
            <div class="col-9">
                <div class="about-content">
                    <h4><em><?= $about->getName()?></em></h4>
                    <?= $about->getContent()?>
                </div>
            </div>
        </div>
    </section>
    <section id="partner">
        <h3><em><?= $about->getPartner()?></em></h3>
        <div class="row">
            <div class="col-3"><img src="./ab_1.png" class="img-fluid" alt=""></div>
            <div class="col-3"><img src="./ab_2.png" class="img-fluid" alt=""></div>
            <div class="col-3"><img src="./ab_3.png" class="img-fluid" alt=""></div>
            <div class="col-3"><img src="./ab_4.png" class="img-fluid" alt=""></div>
        </div>
    </section>
</div>

frontend/views/site/contact.php
<?php

/* @var $contact \common\models\Contacts*/
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = $contact->getTitle();
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="container-fluid wrap-content">
    <section class="block-product">
        <div class="row">
            <div class="col-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.897700320606!2d105.8324560140334!3d21.03677888599402!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135aba15ec15d17%3A0x620e85c2cfe14d4c!2sHo+Chi+Minh+Mausoleum!5e0!3m2!1sen!2s!4v1554305660725!5m2!1sen!2s" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
    </section>
</div>
<div class="container">
    <section id="contact-detail">
        <div class="row">
            <div class="col-sm-4">
                <div class="feature-icon">
                    <i class="far fa-2x fa-paper-plane"></i>
                </div>
                <div class="feature-content">
                    <?= $contact->getContactUs()?>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="feature-icon">
                    <i class="fas fa-2x fa-map-marker-alt"></i>
                </div>
                <div class="feature-content">
                    <?= $contact->getVisit()?>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="feature-icon">
                    <i class="fas fa-2x fa-briefcase"></i>
                </div>
                <div class="feature-content">
                    <?= $contact->getWorkWithUs()?>
                </div>
            </div>
        </div>
    </section>
</div>

frontend/views/site/contact_bak.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/home.php
<?php
/**
 * Created by PhpStorm.
 * User: BIOS
 * Date: 2019-04-10
 * Time: 2:14 PM
 */
use yii\helpers\Url;

$lang = Yii::$app->session->get('lang', 'vi');
$title = ($lang == 'vi') ? 'DÒNG SẢN PHẨM' : 'PRODUCT LINE';
?>

<div class="container">
    <section id="top-banner" class="profile-slider">
        <img src="/images/prof-super.png" class="img-fluid" alt="">
    </section>
    <div class="btn-product-line">
        <a href="#">
            <span><?= $title ?></span>
        </a>
    </div>

</div>

<div class="container-fluid ca-list-product">
    <section class="list-line">
        <div class="row">
            <div class="col-md-2">
                <a href="<?= Url::toRoute(['site/product', 'title' => 'ProFline - ' . \common\helpers\VietnameseUtils::removeSigns(str_replace(" ","-", $title)),'cateId'=> 7])?>">
                    <img src="/images/PROFLINE-NAUJA-300x300.png" alt="">
                </a>
            </div>
            <div class="col-md-2">
                <a href="<?= Url::toRoute(['site/product', 'title' => 'ProFline Medtechnology - ' . \common\helpers\VietnameseUtils::removeSigns(str_replace(" ","-", $title)),'cateId'=> 8])?>">
                    <img src="/images/medtech-300x300.png" alt="">
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <img src="/images/premium-300x300.png" alt="">
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <img src="/images/perfect-300x300.png" alt="">
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <img src="/images/bebe-300x300.png" alt="">
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <img src="/images/sky-pearl-300x300.png" alt="">
                </a>
            </div>
            <div class="col-md-2">
                <a href="#">
                    <img src="/images/amber-300x300.png" alt="">
                </a>
            </div>
        </div>
    </section>
</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;

/* @var $cate \common\models\Category */
/* @var $pro\common\models\Product */
/* @var $listCate*/
/* @var $listProduct*/
/* @var $data*/
$lang = Yii::$app->session->get("lang","vi");
$this->title = 'Profline';
?>
<div class="container wrap-content">

    <section id="top-banner">
        <img src="/image/Visi-produktai-1024x299.png" class="img-fluid" alt="">
    </section>

</div>
<div class="container-fluid ca-list-product">
    <?php foreach($data as $item ) {?>
    <?php // var_dump($item['category_name']);exit;?>
    <section class="block-product">
        <div class="title-category-block">
            <div class="container">
                <h3 class="category-title"><em><?= ($lang == 'vi') ? $item['category_name'] : $item['category_name_en']?></em></h3>
            </div>
        </div>
        <div class="list-product container">
            <div class="row">
                <?php $i = 1; $count = count($item['listProduct']);?>
                <?php $col = 6;?>
                <?php if($count == 1) {
                        $col = 12;
                    } else if($count == 2) {
                        $col = 6;
                    } else if($count == 3) {
                        $col = 4;
                    } else if($count >= 4) {
                        $col = 3;
                    }

                ?>
                <?php foreach($item['listProduct'] as $pro) {?>

                    <div class="box-detail col-md-<?=$col?>">
                        <div class="detail-img">
                            <a href="<?= Url::to(['site/detail','title'=> $pro->getTitle(),'prod'=>$pro->id])?>">
                                <img src="<?= $pro->getThumb()?>" alt="">
                            </a>
                        </div>
                        <div class="product_title entry-title">
                            <span><?=$pro->getName()?></span>
                        </div>
                        <div class="product_title entry-title">
                            <span><?= $pro->size?></span>
                        </div>
                    </div>
                <?php $i++; ?>

                <?php } ?>

            </div>

        </div>
    </section>
    <?php } ?>

<!--
    <section class="block-product">
        <div class="title-category-block">
            <div class="container">
                <h3 class="category-title"><em>Thuốc diệt cỏ</em></h3>
            </div>
        </div>
        <div class="list-product container">
            <div class="row">
                <div class="box-detail col-md-12">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <section class="block-product">
        <div class="title-category-block">
            <div class="container">
                <h3 class="category-title"><em>Thuốc diệt cỏ</em></h3>
            </div>
        </div>
        <div class="list-product container">
            <div class="row">
                <div class="box-detail col-md-4">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
                <div class="box-detail col-md-4">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
                <div class="box-detail col-md-4">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <section class="block-product">
        <div class="title-category-block">
            <div class="container">
                <h3 class="category-title"><em>Thuốc diệt cỏ</em></h3>
            </div>
        </div>
        <div class="list-product container">
            <div class="row">
                <div class="box-detail col-md-3">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
                <div class="box-detail col-md-3">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
                <div class="box-detail col-md-3">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
                <div class="box-detail col-md-3">
                    <div class="detail-img">
                        <img src="http://profline.info/wp-content/uploads/2018/03/universal%C5%ABs-223x300.png" alt="">
                    </div>
                    <div class="product_title entry-title">
                        <span>Skalbimo gelis „Universalus“</span>
                    </div>
                    <div class="product_title entry-title">
                        <span>5L, 1,5 L</span>
                    </div>
                </div>
            </div>

        </div>
    </section>-->
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/news_detail.php
<?php
/**
 * Created by PhpStorm.
 * User: BIOS
 * Date: 2019-04-05
 * Time: 9:00 AM
 */
/** @var $model \common\models\News */
?>
<div class="wrap-content wrap-content-detail">
    <section id="detail-product" class="container">
        <div class="col-12">
            <h1 class="product-title-detail">
                <?= $model->getName() ?>
            </h1>

            <div class="product-detail">
                <?= $model->getContent() ?>
            </div>
        </div>
    </section>

</div>

frontend/views/site/news_list.php
<?php
/**
 * Created by PhpStorm.
 * User: BIOS
 * Date: 2019-04-05
 * Time: 8:40 AM
 */
use yii\helpers\Url;

/** @var $listNews*/
/** @var $paging */
/** @var $new \common\models\News*/
$lang = Yii::$app->session->get('lang', 'vi');
$more = "read more...";
$data = " News is updating...!";
if($lang == 'vi') {
    $more = "Xem tiếp...";
    $data = "Bản tin đang được cập nhật!";
}
?>

<div class="container wrap-content">
    <section class="list-news">
        <?php if(!empty($listNews)) {?>
        <?php foreach($listNews as $new) {?>
        <article class="d-flex flex-row mb-1">
            <div class="thumb-news">
                <a href="<?=Url::toRoute(['site/news-detail','name' => $new->getTitle(),'id'=> $new->id,'nid'=>$new->id])?>"><img  src="<?= $new->getThumb()?>" height="150px" alt=""></a>
            </div>

            <div class="content-news">

                <h5><?= $new->getName()?></h5>
                <p><?=$new->getShortDesc()?></p>
                <a style="float: right" href="<?=Url::toRoute(['site/news-detail','name' => $new->getTitle(),'id'=> $new->id,'nid'=>$new->id])?>"><?= $more?></a>
            </div>
        </article>
        <?php } ?>
        <?php } else {?>
            <span style="color: red"> <?= $data?></span>
        <?php } ?>


    </section>
    <?= \yii\widgets\LinkPager::widget(['pagination' => $paging]) ?>

</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>